import turtle
Steve=turtle.Turtle()
Steve.shape("turtle")
Steve.speed(12)
Steve.pendown()
Steve.fillcolor("chocolate4")
Steve.begin_fill()
Steve.circle(100)
Steve.end_fill()
Steve.right(150)
Steve.fillcolor("chartreuse4")
Steve.begin_fill()
Steve.forward(104)
Steve.right(150)
Steve.forward(80)
Steve.end_fill()
Steve.penup()
Steve.left(50)
Steve.forward(125)
Steve.left(90)
Steve.pendown()
Steve.fillcolor("chartreuse4")
Steve.begin_fill()
Steve.forward(110)
Steve.right(170)
Steve.forward(150)
Steve.end_fill()
Steve.penup()
Steve.left(10)
Steve.forward(30)
Steve.right(20)
Steve.forward(25)
Steve.right(20)
Steve.forward(10)
Steve.pendown()
Steve.fillcolor("mediumseagreen")
Steve.begin_fill()
Steve.circle(50)
Steve.end_fill()
Steve.penup()
Steve.left(90)
Steve.forward(80)
Steve.left(90)
Steve.forward(10)
Steve.pendown()
Steve.fillcolor("darkturquoise")
Steve.begin_fill()
Steve.circle(10)
Steve.end_fill()
Steve.penup()
Steve.right(180)
Steve.forward(20)
Steve.right(90)
Steve.forward(10)
Steve.pendown()
Steve.fillcolor("darkturquoise")
Steve.begin_fill()
Steve.circle(10)
Steve.end_fill()
Steve.penup()
    




